import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'settings': 'Settings',
      'display_name': 'Display Name',
      'display_name_helper': 'This is just for display purpose',
      'account_info': 'Account Information',
      'full_name': 'Full Name',
      'email': 'Email',
      'role': 'Role',
      'save_changes': 'Save Changes',
      'saving': 'Saving...',
      'logout': 'Logout',
      'logout_confirmation': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'app_settings': 'App Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'english': 'English',
      'malay': 'Malay',
      'success_update': 'Settings updated successfully',
      'error_update': 'Error updating settings',
      'please_enter_name': 'Please enter a name',
      'dashboard': 'Dashboard',
      'statistics': 'Statistics',
      'report': 'Report',
      'transactions': 'Transactions',
      'donation_box_wifi': 'Donation Box (Wi-Fi)',
      'users': 'Users',
      'view_all': 'View All',
      'no_transactions_yet': 'No transactions yet',
      'no_transactions_found': 'No transactions found',
      'total': 'Total',
      'today': 'Today',
      'this_month': 'This Month',
      'this_week': 'This Week',
      'this_year': 'This Year',
      'custom': 'Custom',
      'filter_by': 'Filter by:',
      'all': 'All',
      'highlights': 'Highlights',
      'highest_day': 'Highest Day',
      'daily_avg': 'Daily Avg',
      'weekly_trend': 'Weekly Trend',
      'payment_methods': 'Payment Methods',
      'no_data_available': 'No data available',
      'week': 'Week',
      'cash_donation': 'Cash Donation',
      'weekly_donation_report': 'Weekly Donation Report',
      'print_report': 'Print Report',
      'total_donation': 'Total Donation',
      'total_transaction': 'Total Transaction',
      'cash': 'Cash',
      'yesterday': 'Yesterday',
      'last_7_days': 'Last 7 Days',
      'last_30_days': 'Last 30 Days',
      'date_range': 'Date Range',
      'daily_trend': 'Daily Trend',
      'monthly_trend': 'Monthly Trend',
      'yearly_trend': 'Yearly Trend',
      'hourly_trend': 'Hourly Trend',
      'generated_on': 'Generated On',
      'date': 'Date',
      'time': 'Time',
      'method': 'Method',
      'amount': 'Amount',
      'reports': 'Reports',
      'add_user': 'Add User',
      'add_new_user': 'Add New User',
      'username': 'Username',
      'register': 'Register',
      'connect_to_box': 'Connect to Your Donation Box',
      'instruction_1': 'Turn on your Donation Box device.',
      'instruction_2': 'Tap the button below to open Wi-Fi settings.',
      'instruction_3': 'Connect to the Wi-Fi network named "SadaqahLink".',
      'instruction_4': 'Enter the password if prompted (default: 12345678).',
      'open_wifi': 'Open Wi-Fi Settings',
      'search_users': 'Search users...',
      'no_users_found': 'No users found',
      'delete_user': 'Delete User',
      'delete_user_confirmation': 'Are you sure you want to delete',
      'delete': 'Delete',
      'edit': 'Edit',
      'edit_user': 'Edit User',
      'user_removed': 'User removed from database',
      'error_deleting_user': 'Error deleting user',
      'user_created': 'User created & password reset email sent',
      'user_updated': 'User updated successfully',
      'done': 'Done',
      'admin': 'Admin',
      // 'ajk': 'AJK', // Removed duplicate
      'internet_error': 'Please check your internet connection',
    },
    'ms': {
      'settings': 'Tetapan',
      'display_name': 'Nama Paparan',
      'display_name_helper': 'Ini hanya untuk tujuan paparan',
      'account_info': 'Maklumat Akaun',
      'full_name': 'Nama Penuh',
      'email': 'Emel',
      'role': 'Peranan',
      'save_changes': 'Simpan Perubahan',
      'saving': 'Menyimpan...',
      'logout': 'Log Keluar',
      'logout_confirmation': 'Adakah anda pasti mahu log keluar?',
      'cancel': 'Batal',
      'app_settings': 'Tetapan Aplikasi',
      'language': 'Bahasa',
      'dark_mode': 'Mod Gelap',
      'english': 'Inggeris',
      'malay': 'Melayu',
      'success_update': 'Tetapan berjaya dikemaskini',
      'error_update': 'Ralat mengemaskini tetapan',
      'please_enter_name': 'Sila masukkan nama',
      'dashboard': 'Papan Pemuka',
      'statistics': 'Statistik',
      'report': 'Laporan',
      'transactions': 'Transaksi',
      'donation_box_wifi': 'Tabung Derma (Wi-Fi)',
      'users': 'Pengguna',
      'view_all': 'Lihat Semua',
      'no_transactions_yet': 'Tiada transaksi lagi',
      'no_transactions_found': 'Tiada transaksi ditemui',
      'total': 'Jumlah',
      'today': 'Hari Ini',
      'this_month': 'Bulan Ini',
      'this_week': 'Minggu Ini',
      'this_year': 'Tahun Ini',
      'custom': 'Tersuai',
      'filter_by': 'Tapis mengikut:',
      'all': 'Semua',
      'highlights': 'Sorotan',
      'highest_day': 'Hari Tertinggi',
      'daily_avg': 'Purata Harian',
      'weekly_trend': 'Trend Mingguan',
      'payment_methods': 'Kaedah Pembayaran',
      'no_data_available': 'Tiada data tersedia',
      'week': 'Minggu',
      'cash_donation': 'Derma Secara Tunai',
      'weekly_donation_report': 'Laporan Mingguan',
      'print_report': 'Cetak Laporan',
      'total_donation': 'Jumlah Derma',
      'total_transaction': 'Jumlah Transaksi',
      'cash': 'Tunai',
      'yesterday': 'Semalam',
      'last_7_days': '7 Hari Lepas',
      'last_30_days': '30 Hari Lepas',
      'date_range': 'Julat Tarikh',
      'daily_trend': 'Trend Harian',
      'monthly_trend': 'Trend Bulanan',
      'yearly_trend': 'Trend Tahunan',
      'hourly_trend': 'Trend Setiap Jam',
      'generated_on': 'Dijana Pada',
      'date': 'Tarikh',
      'time': 'Masa',
      'method': 'Kaedah',
      'amount': 'Jumlah',
      'reports': 'Laporan',
      'add_user': 'Pengguna Baru',
      'add_new_user': 'Tambah Pengguna',
      'username': 'Nama Panggilan',
      'register': 'Daftar',
      'connect_to_box': 'Sambung ke Tabung Derma Anda',
      'instruction_1': 'Hidupkan peranti Tabung Derma anda.',
      'instruction_2': 'Tekan butang di bawah untuk membuka tetapan Wi-Fi.',
      'instruction_3': 'Sambung ke rangkaian Wi-Fi bernama "SadaqahLink".',
      'instruction_4': 'Masukkan kata laluan jika diminta (lalai: 12345678).',
      'open_wifi': 'Buka Tetapan Wi-Fi',
      'search_users': 'Cari pengguna...',
      'no_users_found': 'Tiada pengguna ditemui',
      'delete_user': 'Padam Pengguna',
      'delete_user_confirmation': 'Adakah anda pasti mahu memadam',
      'delete': 'Padam',
      'edit': 'Sunting',
      'edit_user': 'Sunting Pengguna',
      'user_removed': 'Pengguna dipadam dari pangkalan data',
      'error_deleting_user': 'Ralat memadam pengguna',
      'user_created':
          'Pengguna dicipta & emel tetapan semula kata laluan dihantar',
      'user_updated': 'Pengguna berjaya dikemaskini',
      'done': 'Selesai',
      'admin': 'Admin',
      'ajk': 'AJK',
      'user_restore_queued':
          'Pemulihan pengguna dalam barisan. Emel tetapan semula kata laluan telah dihantar.',
      'internet_error': 'Sila semak sambungan internet anda',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ms'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
